server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/villion_auth?serverTimezone=Asia/Seoul
    root: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret:ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd